# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='invited',
            field=models.ManyToManyField(related_name='trips_invited_to', to='trips.User'),
        ),
    ]
